name: Content Change Request
description: Request new content or changes from DevX.
title: '[Content Change Request]: '
labels: 'content-change-request'
assignees:
  - lucas-tortora
body:
- type: dropdown
  attributes:
    label: Request Type
    options:
      - New Content
      - Modify Content
  validations:
    required: true
- type: dropdown
  attributes:
    label: Content Type
    description: Check out https://diataxis.fr/ if the options are not clear.
    options:
      - Explanation
      - Reference
      - How-To
      - Tutorial (Text/Video)
      - Other
  validations:
    required: true
- type: dropdown
  attributes:
    label: Wiki Section Target
    options:
      - Get Started
      - Learn
      - Build
      - Maintain
      - Other
- type: dropdown
  attributes:
    label: Layer
    options:
      - Layer 1 - Tangle/DAG
      - Layer 2 - ISC & etc.
      - Not Applicable
- type: checkboxes
  id: due-dilligence
  attributes:
    label: Content Plan Checked
    description: "Whether you checked [content plan board](https://miro.com/app/board/uXjVMD1bkow=/) pw: RcL[?p?38ChF(5s9Cad9&8270"
    options:
      - label: Affirmative
- type: textarea
  attributes:
    label: Description
