name: Content Change Request
description: Request new content or changes from DevX.
title: '[Change Request]: '
labels: 'change-request'
assignees:
  - lucas-tortora
body:
- type: dropdown
  attributes:
    label: Request Type
    options:
      - New Content
      - Alter Content
  validations:
    required: true
- type: dropdown
  attributes:
    label: Content Type
    description: Check out https://diataxis.fr/ if the options are not clear.
    options:
      - Explanation
      - Reference
      - How-To
      - Tutorial (Text/Video)
      - Other
  validations:
    required: true
- type: dropdown
  attributes:
    label: Wiki Section Target
    options:
      - Get Started
      - Learn
      - Build
      - Maintain
      - Other
- type: dropdown
  attributes:
    label: Layer
    options:
      - Layer 1 - Tangle/DAG
      - Layer 2 - ISC & etc.
      - Not Applicable
- type: checkboxes
  id: Due Dilligence
  attributes:
    label: |
      I checked the ![content plan board](https://miro.com/app/board/uXjVMD1bkow=/) pw: RcL[?p?38ChF(5s9Cad9&8270
    description: Whether you checked the content plan board and figured out where the content should live
    options:
      - label: Yes
- type: textarea
  attributes:
    label: Description
